### ISSUE TITLE
Calculating length_in_pixels

### ISSUE THREAD

**Issue by evros-chris** [zubu007/auto-subtitle-generator#3]
I believe that in the two lines below `length_in_pixels` should be:

`length_in_pixels = (len(words[i]) + 1) * self.char_width`

so that you take into account the spaces between the words bro:)

https://github.com/zubu007/auto-subtitle-generator/blob/f08f780ff7f8bc761cdb2992666ffed239db7480/main.py#L51
https://github.com/zubu007/auto-subtitle-generator/blob/f08f780ff7f8bc761cdb2992666ffed239db7480/main.py#L59

**Comment by zubu007** [comment]
If you want to fix this, open a pull request. If not i will add this later. thanks for the input.

**Comment by evros-chris** [comment]
Thank you, I have opened the pull request
